version: 2.1

jobs:
    test:
        docker:
            - image: jcgq/mii_cc_ugr:latest
        steps:
            - checkout
            - run: docker run -t -v `pwd`:/app/test jcgq/mii_cc_ugr
          
workflows:
    test_project:
        jobs:
            - test