version: 2.1

jobs:
    test:
        docker:
            - image: circleci/python:3.10
        steps:
            - checkout
            - run: python setup.py -q install
            - run: invoke test
          
workflows:
    test_project:
        jobs:
            - test