jobs:
    test:
        docker:
            - image: jcgq/mii_cc_ugr:latest
        steps:
            - checkout
            - run: invoke test

            
workflows:
    test_project:
        jobs:
            - test