name: Recetarium

#Se activa cuando se realiza un push a alguno de los fucheros de paths
on:
  push:
    paths:
      - ".github/workflows/latest.yml"
      - "recetarium/recetas.py"
      - "recetarium/funciones.py"
      - "recetarium/excepciones.py"
      - "test/test.py"
      - "Dockerfile"

jobs:
  push_to_registry:
    name: Subo el Docker a Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Chequear el repositorio
        uses: actions/checkout@v2

      - name: Nos logueamos en Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extraemos los metadatos (tags y etiquetas) para Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          #Se añade la etiqueta latest (Para evitar que ponga main)
          tags: latest
          images: jcgq/mii_cc_ugr

      - name: Construimos y subimos la imagen a Docker Hub
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}