name: test

on:
  push:
    paths:
      - ".github/workflows/test_InCon.yml"
      - "recetarium/*"
      - "test/*"
      - "Dockerfile"
      - "json/*"

jobs:
  lanzar_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: lanzar test
        run:
          docker pull jcgq/mii_cc_ugr
        run:
          docker run -t -v `pwd`:/app/test jcgq/mii_cc_ugr