name: test

on:
  push:
    paths:
      - ".github/workflows/test_InCon.yml"
      - "recetarium/recetas.py"
      - "recetarium/funciones.py"
      - "test/test.py"
      - "Dockerfile"

jobs:
  lanzar_test:
    runs-on: ubuntu-latest
    container: 
    image: jcgq/mii_cc_ugr

    steps:
      - uses: actions/checkout@v2

      - name: lanzar test
        run:
          invoke test