name: test

on:
  push:
    paths:
      - ".github/workflows/test_InCon.yml"
      - "recetarium/recetas.py"
      - "recetarium/funciones.py"
      - "test/test.py"
      - "Dockerfile"

jobs:
  lanzar_test:
    runs-on: ubuntu-latest
    container: jcgq/mii_cc_ugr

    steps:
      - name: Crea infra para checkout
        run: sudo mkdir -p /__w/MII_CC_UGR/MII_CC_UGR && sudo chmod 777 /__w/MII_CC_UGR/MII_CC_UGR
      - uses: actions/checkout@v2

      - name: lanzar test
        run:
          invoke test